# ================= SERVER =================
server.port=8082

# ================= DATABASE =================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/bankmanagementdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ================= AUTH SERVICE =================
auth.service.base-url=${AUTH_SERVICE_BASE_URL:http://bank-auth-service:9090}

# ================= LOGGING =================
logging.level.org.hibernate.SQL=DEBUG
logging.level.com.bank.account=DEBUG

# ================= APP NAME =================
spring.application.name=bank-account-service

jwt.secret=ThisIsMyVerySecretKeyForBankManagementSystem2026
