server.port=8084

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/bankmanagementdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.show-sql=true

account.service.base-url=${ACCOUNT_SERVICE_BASE_URL:http://bank-account-service:8082}
transaction.service.base-url=${TRANSACTION_SERVICE_BASE_URL:http://transfer-flow-service:8083}

twilio.account-sid=YOUR_TWILIO_ACCOUNT_SID
twilio.auth-token=YOUR_TWILIO_AUTH_TOKEN
twilio.phone-number=YOUR_TWILIO_PHONE_NUMBER

spring.application.name=bank-ivr-service
