# --- Server ---
server.port=8083

# --- Account Service integration (WebClient base URL) ---
account.service.url=${ACCOUNT_SERVICE_URL:http://bank-account-service:8082}
fraud.api.url=${FRAUD_API_URL:http://fraud-detection-service:5000/api/Fraud/check}

# --- MySQL ---
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/bankmanagementdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
